# -*- coding: utf-8 -*-
"""AI recommender.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NSG8CSbw8bv6P2mUHQUZC7bAzxLy4ro5
"""

import pandas as pd
import math
from collections import Counter


class CareerRecommender:
    def __init__(self, csv_path):
        self.df = pd.read_csv(csv_path)

        self.roles = self.df["job_role"].tolist()
        self.skills = self.df["skills"].apply(lambda x: x.split(",")).tolist()
        self.categories = self.df["category"].tolist()
        self.levels = self.df["level"].tolist()
        self.salaries = self.df["salary"].tolist()

        self.build_vocab()
        self.build_vectors()

    def build_vocab(self):
        all_skills = set()
        for s in self.skills:
            all_skills.update([x.strip().lower() for x in s])
        self.vocab = sorted(list(all_skills))

    def build_vectors(self):
        self.idf = {}
        total_docs = len(self.skills)

        for skill in self.vocab:
            doc_count = sum(1 for s in self.skills if skill in [x.strip().lower() for x in s])
            self.idf[skill] = math.log((total_docs + 1) / (doc_count + 1)) + 1

        self.vectors = []
        for s in self.skills:
            tf = Counter([x.strip().lower() for x in s])
            vec = []
            for skill in self.vocab:
                vec.append(tf.get(skill, 0) * self.idf[skill])
            self.vectors.append(vec)

    def cosine(self, a, b):
        dot = sum(x*y for x, y in zip(a, b))
        mag1 = math.sqrt(sum(x*x for x in a))
        mag2 = math.sqrt(sum(y*y for y in b))
        return dot / (mag1 * mag2 + 1e-9)

    def recommend(self, user_skills):
        user_skills = [s.lower() for s in user_skills]
        tf = Counter(user_skills)

        user_vec = []
        for skill in self.vocab:
            user_vec.append(tf.get(skill, 0) * self.idf[skill])

        results = []

        for i in range(len(self.roles)):
            score = self.cosine(user_vec, self.vectors[i])

            role_skills = [x.strip().lower() for x in self.skills[i]]

            matched = [s for s in user_skills if s in role_skills]
            missing = [s for s in role_skills if s not in user_skills]

            results.append({
                "role": self.roles[i],
                "score": score,
                "category": self.categories[i],
                "level": self.levels[i],
                "salary": self.salaries[i],
                "matched": matched,
                "missing": missing
            })

        results.sort(key=lambda x: x["score"], reverse=True)
        return results[:3]



"""# New Section"""