# -*- coding: utf-8 -*-
"""classification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NSG8CSbw8bv6P2mUHQUZC7bAzxLy4ro5
"""

# 1. Import required libraries
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix, classification_report, f1_score, accuracy_score

# 2. Load and understand the data
iris = load_iris()
X = iris.data
y = iris.target

df = pd.DataFrame(X, columns=iris.feature_names)
df['species'] = y

print("=" * 50)
print("Step 1: Load and Understand the Data")
print("=" * 50)
print(f"Number of samples: {df.shape[0]}")
print(f"Number of features: {df.shape[1] - 1}")
print(f"Number of classes: {len(np.unique(y))}")
print("\nFirst 5 rows of data:")
print(df.head())
print("\nQuick statistics:")
print(df.describe())

# 3. Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42, stratify=y
)

print("\n" + "=" * 50)
print("Step 2: Split the Data")
print("=" * 50)
print(f"Training set size: {X_train.shape[0]} samples")
print(f"Testing set size: {X_test.shape[0]} samples")

# 4. Apply Feature Scaling (StandardScaler)
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

print("\n" + "=" * 50)
print("Step 3: Apply Scaling (StandardScaler)")
print("=" * 50)
print("Data transformed to:")
print(f"- Mean = 0")
print(f"- Variance = 1")

# 5. Apply KNN Algorithm
k = 5
model = KNeighborsClassifier(n_neighbors=k)
model.fit(X_train_scaled, y_train)

# 6. Make predictions
y_pred = model.predict(X_test_scaled)

print("\n" + "=" * 50)
print(f"Step 4: Apply KNN Algorithm (k={k})")
print("=" * 50)

# 7. Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred, average='weighted')
conf_matrix = confusion_matrix(y_test, y_pred)

print(f"\n Accuracy: {accuracy:.4f}")
print(f" F1 Score (Weighted): {f1:.4f}")
print("\n Classification Report:")
print(classification_report(y_test, y_pred, target_names=iris.target_names))

print("\n Confusion Matrix:")
print(conf_matrix)

# 8. Analyze results
print("\n" + "=" * 50)
print("Results Analysis")
print("=" * 50)
if accuracy > 0.95:
    print(" Model performance is excellent - over 95% accuracy")
else:
    print(" Model can be improved by tuning parameters or trying other algorithms")

print("\n Example prediction on a new sample:")
new_sample = np.array([[5.1, 3.5, 1.4, 0.2]]) 
new_sample_scaled = scaler.transform(new_sample)
prediction = model.predict(new_sample_scaled)
print(f"Sample: {new_sample[0]}")
print(f"Prediction: {iris.target_names[prediction[0]]}")

